services:
  app:
    image: golang:1.25-alpine
    container_name: password_manager_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["go", "run", "./main.go"]
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/password_manager?sslmode=disable
      - JWT_SECRET=your_jwt_secret_here
      - EMAIL_USER=example@gmail.com
      - EMAIL_PASS=your_email_password
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: password_manager_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: password_manager
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
