// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Password struct {
	ID        int64
	UserID    int64
	Service   string
	Username  string
	Password  string
	Url       sql.NullString
	Notes     sql.NullString
	Icon      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
