// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Password struct {
	ID        int64
	Name      string
	Password  string
	UserID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Url          sql.NullString
	Notes        sql.NullString
	Icon         sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
