// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: passwords.sql

package sqlc

import (
	"context"
	"time"
)

const createPassword = `-- name: CreatePassword :one
INSERT INTO passwords (
    user_id,
    name,
    password
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, created_at, updated_at
`

type CreatePasswordParams struct {
	UserID   int64
	Name     string
	Password string
}

type CreatePasswordRow struct {
	ID        int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreatePassword(ctx context.Context, arg CreatePasswordParams) (CreatePasswordRow, error) {
	row := q.db.QueryRowContext(ctx, createPassword, arg.UserID, arg.Name, arg.Password)
	var i CreatePasswordRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePassword = `-- name: DeletePassword :one
DELETE FROM passwords
WHERE id = $1
    AND user_id = $2
RETURNING id, user_id, created_at, updated_at
`

type DeletePasswordParams struct {
	ID     int64
	UserID int64
}

type DeletePasswordRow struct {
	ID        int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) DeletePassword(ctx context.Context, arg DeletePasswordParams) (DeletePasswordRow, error) {
	row := q.db.QueryRowContext(ctx, deletePassword, arg.ID, arg.UserID)
	var i DeletePasswordRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordByID = `-- name: GetPasswordByID :one
SELECT id, name, password, user_id, created_at, updated_at FROM passwords
WHERE id = $1
    AND user_id = $2
LIMIT 1
`

type GetPasswordByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetPasswordByID(ctx context.Context, arg GetPasswordByIDParams) (Password, error) {
	row := q.db.QueryRowContext(ctx, getPasswordByID, arg.ID, arg.UserID)
	var i Password
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Password,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPasswords = `-- name: ListPasswords :many
SELECT id, name, password, user_id, created_at, updated_at FROM passwords
WHERE user_id = $1
`

func (q *Queries) ListPasswords(ctx context.Context, userID int64) ([]Password, error) {
	rows, err := q.db.QueryContext(ctx, listPasswords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Password
	for rows.Next() {
		var i Password
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Password,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE passwords
SET 
    name = $3,
    password = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, name, created_at, updated_at
`

type UpdatePasswordParams struct {
	ID       int64
	UserID   int64
	Name     string
	Password string
}

type UpdatePasswordRow struct {
	ID        int64
	UserID    int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (UpdatePasswordRow, error) {
	row := q.db.QueryRowContext(ctx, updatePassword,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Password,
	)
	var i UpdatePasswordRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
