name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: password_manager
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd "pg_isready -U postgres"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.25

            - name: Install migrate CLI
              run: |
                  curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
                  sudo mv migrate /usr/local/bin/migrate

            - name: Wait for Postgres
              run: |
                  until pg_isready -h localhost -p 5432 -U postgres; do
                    echo "Waiting for Postgres..."
                    sleep 2
                  done

            - name: Run migrations
              run: |
                  migrate -path db/migration -database "postgres://postgres:postgres@localhost:5432/password_manager?sslmode=disable" -verbose up

            - name: Build Go app
              run: go build -v ./...
