name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16-alpine
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: password_manager
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd "pg_isready -U postgres" 
                    --health-interval 10s 
                    --health-timeout 5s 
                    --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.25"

            - name: Build Go app
              run: |
                  go mod download
                  go build -o password-manager ./main.go

            - name: Wait for Postgres
              run: |
                  echo "Waiting for Postgres..."
                  until pg_isready -h localhost -p 5432 -U postgres; do
                    sleep 1
                  done

            - name: Run migrations
              run: |
                  ./tools/migrate -path db/migration -database "postgres://postgres:postgres@localhost:5432/password_manager?sslmode=disable" -verbose up

            - name: Run tests
              run: |
                  go test ./...
